
name: abd
channels:
  - conda-forge
  - pytorch
  - defaults
  - rapidsai
  - nvidia
dependencies:
  # Required Dependencies
  - python=3.10.*
  - pytorch
  - pytorch-lightning # Minor changes might be needed for a later version of the pytorch ligthning library.
  - pyyaml
  - torchvision
  - scikit-learn
  - pandas
  - tqdm
  - pip
  - rapids
  - gpytorch>=1.11
  - pip:
    - tape-proteins==0.5
    - gpytorch==1.4.1
    - hydra-core>=1.0
    - hydra-submitit-launcher>=1.0
    - seaborn
    - onnx
    - onnxruntime
