#defaults:
    #- override hydra/launcher: submitit_slurm

experiment_name: "train_bcrh_cdr3aa"
hydra:
    run:
        dir: ./results/${experiment_name}
############

model_cfg:
    _target_: src.models.ExactGP.GPRegressionModel
    lr: 0.001
    num_epochs: 1000
    inducing_points: null

feat_cfg:
    _target_: src.models.feat_extraction.FeatExtractor
    model_config_file: /mnt/jimmyxu/nfs_share2/Documents/biotransfer/pretrained_models/bert_configs/config.json
    feat_path: /mnt/jimmyxu/nfs_share2/Documents/biotransfer/pretrained_models/pfam.ckpt # Full path to the pretrained langauge model checkpoint
    strict_reload: False
    variable_regions: False
    pca_dim: 1024

train_set_cfg:
    _target_: src.datasets.CovidDataset
    data_path: /mnt/jimmyxu/nfs_share2/Documents/biotransfer/example_data/covid/
    split: train
    chain: 14H
    average_replicates: True
    add_static_ends: True
    correction: replicate
    filter_nan: median

train_dataloader_cfg:
    batch_size: 32
    shuffle: True


eval_set_cfg:
    _target_: src.datasets.CovidDataset
    data_path: /mnt/jimmyxu/nfs_share2/Documents/biotransfer/example_data/covid/
    split: test
    chain: BCRH_cdr3aa
    average_replicates: True
    add_static_ends: True
    correction: replicate
    filter_nan: median

eval_dataloader_cfg:
    batch_size: 32
    shuffle: True

