#defaults:
    #- override hydra/launcher: submitit_slurm

experiment_name: "BCRH-P-M004"
hydra:
    run:
        dir: ./results/${experiment_name}
############

model_cfg:
    _target_: src.models.ExactGP.GPRegressionModel
    lr: 0.001
    num_epochs: 1000
    inducing_points: null

feat_cfg:
    _target_: src.models.feat_extraction.FeatExtractor
    model_config_file: /ssd/users/zx243/Documents/biotransfer/pretrained_models/bert_configs/config.json
    feat_path: /ssd/users/zx243/Documents/biotransfer/pretrained_models/pfam.ckpt # Full path to the pretrained langauge model checkpoint
    strict_reload: False
    variable_regions: False
    pca_dim: null

train_set_cfg:
    _target_: src.datasets.BCRDataset
    data_path: /ssd/users/zx243/Documents/biotransfer/example_data/bcr/
    split: train
    average_replicates: False
    chain: IGH
    add_static_ends: False
    filter_nan: drop

train_dataloader_cfg:
    batch_size: 32
    shuffle: True


eval_set_cfg:
    _target_: src.datasets.BCRDataset
    data_path: /ssd/users/zx243/Documents/biotransfer/example_data/bcr/
    split: test
    chain: IGH
    average_replicates: False
    add_static_ends: False
    filter_nan: drop

eval_dataloader_cfg:
    batch_size: 32
    shuffle: True

